### ISSUE TITLE
Login can be multiple

### ISSUE THREAD

**Issue by ComeBurguburu** [loicortola/training-chat-rest#1]
Two accounts can have the same login

**Comment by loicortola** [comment]
Thanks for the issue
not sure what you are talking about. can you be more specific?
light equality protection has been implemented here:
https://github.com/loicortola/training-chat-rest/blob/master/service/login-service.js#L45
although a trim() should be done for more security.

Only security breach is that one can post a message while providing another login. Being fixed.

**Comment by loicortola** [comment]
Solved in commit https://github.com/loicortola/training-chat-rest/commit/a77ed6acbfda62bec38aadd434635c1e812d867d
